### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by christiancompton** [IBM/tone-analyzer-ios#1]
1. This will not compile:  https://github.com/IBM/tone-analyzer-ios/blob/master/toneanalyzerios/AppDelegate.swift#L21 see the same issue in MBaaS.

1. When instructing the service creation, there is a reference to Cloudant IAM credentials that must be removed.

1. This suffers from the same problem as visual recognition with the 0.37.0 watson SDK and Xcode9 support.

**Comment by dolph** [comment]
1 should be addressed by https://github.com/IBM/tone-analyzer-ios/commit/7b24ab2d31ff326ecea41a3939cf979dc7d2ee47

**Comment by christiancompton** [comment]
Closing as complete.
